---

- hosts: all
  become: true
  tasks:

# variables declared inside inventory for each OS

  - name: install apache and php package, and update_cache.
    package: # istället för apt och dnf
      name:
        - "{{ apache_package }}" # detta är en variable
        - "{{ php_package }}"  # detta är en variable
      state: latest
      update_cache: yes





