---


- hosts: all   # Kör play updates på alla hosts
  become: true
  pre_tasks:  # denna task körs alltid först innan andra plays, dvs uppdatera först sedan installera.

  - name: update repo index (CentOS) # installerar updates på CentOS (dnf)
    tags: always # kör alltid
    dnf:
      update_cache: yes
    changed_when: false # ignorera update changes för cleaner output resultat
    when: ansible_distribution == "CentOS"

  - name: update repo index (Ubuntu) # installerar updates på ubuntu (apt)
    tags: always # Kör alltid
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all # kör base role på alla servrar
  become: true
  roles:
    - base # körs på alla servrar i inventory.

- hosts: workstations # kör workstation role på workstation servrar
  become: true
  roles:
    - workstations # namnet på rolen vi ska köra, kommer enbart utföras på workstation servrar.

- hosts: web_servers
  become: true
  roles:
    - web_servers # körs enbart på servrar som ligger i gruppen web_servers i inventory.

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers










