- name: install apache and php packages # play för både ubuntu och centos i samma.
  tags: apache,httpd,php
  package:
    name:
      - "{{ apache_package_name }}" # variabel vi deklarerat i host_vars IP.yml filerna
      - "{{ php_package_name }}" # variabel vi deklarerat i host_vars IP.yml filerna
    state: latest


- name: start and enable apache/httpd service # ubuntu autostartar apache vid install, men ej centos.
  tags: apache,httpd
  service:
    name: "{{ apache_service }}" # variabel vi deklarerat i host_vars IP.yml filerna
    state: started
    enabled: yes # aktiver autostart


- name: change e-mail address for admin # ändra en rad i httpd.conf och ersätt med något annat
  tags: apache,centos,httpd
  lineinfile: # ändra en rad i en fil
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin' # regex för att hitta raden som börjar på ServerAdmin
    line: ServerAdmin somebody@somewhere.com # ändra ovan rad att bli detta istället, ersätter root@localhost.com
  when: ansible_distribution == "CentOS"
  notify: restart_apache # måste stämma överens med - name: restart_apache i /web_servers/handleres/main.yml


- name: copy default html file for site # kopiera default_site till index.html på alla web_servers
  tags: apache,apache2,httpd # tags för att lättare targetta denna file copy.
  copy: # använd module copy för att kopiera en fil till en server.
    src: default_site.html # filen som ska kopieras. OBS man behöver ej ange directory files den ligger i.
    dest: /var/www/html/index.html # var den ska hamna på servern vi kopierar till. OBS, filnamnet behöver inte vara lika. Detta blir filnamnet vår fil får efter att den kopierats över.
    owner: root # vem som ska äga filen, skulle kunna vara www-user eller vilken apache user vi har.
    group: root # gruppen som ska ha tillgång till filen.
    mode: 0644  # rw-r--r--  rättigheter, owner-group-others.
