- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEFgHwvtLsseQd4jL7mw/cKysrb/jkTvzd1TGUmFsNoS ansible"

- name: generate sshd_config file from a template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd # variabel som ska skickas till handler
